export const TOGGLE_DARKMODE = 'TOGGLE_DARKMODE';

export const CREATE_PROJECT = 'CREATE_PROJECT';

export const AUTH_START = 'AUTH_START';
export const AUTH_END = 'AUTH_END';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const CLEAN_MESSAGE = 'CLEAN_MESSAGE';

export const VERTIFY_START = 'VERTIFY_START';
export const VERTIFY_SUCCESS = 'VERTIFY_SUCCESS';
export const VERTIFY_FAIL = 'VERTIFY_FAIL';

export const RECOVERY_START = 'RECOVERY_START';
export const RECOVERY_SUCCESS = 'RECOVERY_SUCCESS';
export const RECOVERY_FAIL = 'RECOVERY_FAIL';
